data_type: CLN_PRT_MIR_MET
discovery_dir_name: Training
omics_list:
- CLNData_CG.pkl
- PRTData_CG.pkl
- MIRData_CG.pkl
- METData_CG.pkl
omics_parent_dir: ./data/main_data/cg/
validation_dir_name: Validation
